### ISSUE TITLE
chartWrapper is undefined?

### ISSUE THREAD

**Issue by eudennis** [ejfrias/Frappe-Charts-Ionic-3#1]
I followed your instruction, but in the frappe-charts.ts I got that erro:

"Uncaught (in promise): TypeError: this.chartWrapper is undefined [..]"

What exactly the line "  @ViewChild('chartWrapper') chartWrapper;" should do?

Thanks :)

**Comment by ejfrias** [comment]
That line points to `<div #chartWrapper></div>` in /src/components/frappe-charts/frappe-charts.html. It's case sensitive.

**Comment by eudennis** [comment]
It worked now! The problem was exactly that. Thanks
