### ISSUE TITLE
Updating Values

### ISSUE THREAD

**Issue by eudennis** [ejfrias/Frappe-Charts-Ionic-3#2]
It's me again :) I was able to generate the chart, but I'm not really sure how to update it. I saw that there is an update method in the library, but I'm not able to access it through my component.

It should be something similar to that?

`this.chartCtrl.chart.update_values(...)`

**Comment by ejfrias** [comment]
Not sure why the update_values() is not available right away in the `this.chartCtrl.chart`, I can see that it is buried deep down the prototypes though. 

I have one solution in mind. You can pass your new values in `this.chartCtrl.params` or `this.chartCtrl.params.labels = newLabels` then call the `this.chartCtrl.renderChart()`. This will basically replace the parameters and re-draw the chart.

Something like this:
```javascript
let newLabels = ["2am", "4am", "6am", "8am", "10am", "12pm", "14pm", "16pm"];
let newDatasets = [
	{
		title: "Some Data",
		color: "light-blue",
		values: [5, 10, 15, 20, 25, 30, 35, 40]
	},
	{
		title: "Another Set",
		color: "violet",
		values: [20, 40, 60, 80, 100, 90, 70, 50]
	}
];

this.chartCtrl.params.data.labels = newLabels;
this.chartCtrl.params.data.datasets = newDatasets;
this.chartCtrl.renderChart();
```

**Comment by ejfrias** [comment]
Closing this. Please re-open if you still having issues. Cheers
